[project]
name = "etcs-openai-like-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.116.1",
    "novelai-api>=0.34.1",
    "openai>=1.107.0",
    "uvicorn>=0.35.0",
]
