name: Sync to Hg

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 检出 GitHub 仓库代码
      - name: Checkout GitHub repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      # 将代码推送到 Huggingface
      - name: Push to GitLab
        env:
          HG_URL: ${{ secrets.HG_URL }}
        run: |
          git remote set-url origin ${HG_URL} 
          git push --force origin HEAD:main